spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/webservice_sample?useUnicode=true&characterEncoding=utf8
        databaseName:
        serverName:
        username: root
        password:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    slavedatasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/webservice_sample_slave?useUnicode=true&characterEncoding=utf8
        databaseName:
        serverName:
        username: root
        password:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        properties:
                    hibernate.cache.use_second_level_cache: false
                    hibernate.cache.use_query_cache: false
                    hibernate.generate_statistics: true
                    org.hibernate.envers.audit_table_suffix: _history

envConfig:
    fixerServiceUrl: http://api.fixer.io/latest

http:
    cache:
        timeToLiveInDays: 31

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M