server:
    port: 8080

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

swagger:
    title: Sample Webservice Swagger
    description: Swagger API's for Sample webservice
    version: 0.0.1
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
